FROM ubuntu:20.04

RUN sudo apt-get update && sudo apt upgrade -y
RUN sudo apt-get install make build-essential gcc curl git jq chrony -y

RUN curl -OL https://golang.org/dl/go1.18.2.linux-amd64.tar.gz

RUN tar -C /usr/local -xvf go1.18.2.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin:$HOME/go/bin

ENV GOROOT=/usr/local/go
ENV GOPATH=$HOME/go
ENV GO111MODULE=on





RUN git clone -b v7.0.1  http://github.com/cosmos/gaia
RUN cd gaia && make install

ENV PATH=$PATH:/root/go/bin

RUN echo gaiad version --long


